name: dat_lich_kham
description: Ứng dụng đặt lịch khám bệnh (Mobile + Web) theo kiến trúc MVC.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.17
  file_picker: ^8.3.7
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

